version: '3.7'

services:
  php7.1:
    image: php:7.1.3-fpm
    build:
      context: ./docker/php7.1
    hostname: php7.1
    ports:
      - "10003:9000"
    volumes:
      - ./projects/:/var/www/html/
      - ./docker/php7.1/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php7.1/php.ini:/usr/local/etc/php/php.ini

    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  php7.2:
    build:
      context: ./docker/php7.2
    hostname: php7.2
    ports:
      - "10010:9000"
      - "6003:6003"
    volumes:
      - ./projects/:/var/www/html/
      - ./docker/php7.2/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php7.2/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  php7.3:
    image: php:7.3-fpm
    build:
      context: ./docker/php7.3
    hostname: php7.3
    ports:
      - "10005:9000"
    volumes:
      - ./projects/:/var/www/html/
      - ./docker/php7.3/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php7.3/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend

    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  php7:
    image: php:7.4-fpm
    build:
      context: ./docker/php7
    hostname: php7
    ports:
      - "10001:9000"
    volumes:
      - ./projects/:/var/www/html/
      - ./docker/php7/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php7/php.ini:/usr/local/etc/php/php.ini

    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  php8:
      build:
          context: ./docker/php8
      hostname: php8
      ports:
        - "10000:9000"
      volumes:
        - ./projects/:/var/www/html/
        - ./docker/php8/www.conf:/usr/local/etc/php-fpm.d/www.conf
        - ./docker/php8/php.ini:/usr/local/etc/php/php.ini
      environment:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      networks:
        - backend
  php8.1:
    build:
      context: ./docker/php8.1
    hostname: php8.1
    ports:
      - "10002:9000"
      - "6001:6001"
    volumes:
      - ./projects/:/var/www/html/
      - ./docker/php8.1/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php8.1/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  php8.2:
    build:
      context: ./docker/php8.2
    hostname: php8.2
    ports:
      - "10006:9000"
      - "6002:6002"
    volumes:
      - ./projects/:/var/www/html/
      - ./docker/php8.2/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php8.2/php.ini:/usr/local/etc/php/php.ini

    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  nginx:
        platform: linux/x86_64
        image: nginx:1.13.8
        ports:
          - "80:80"
          - "8000:8000"
          - "8888:8888"
        volumes:
          - ./projects/:/var/www/html/
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - php8.1
          - php8.2
        networks:
          - backend
  mysql:
        platform: linux/x86_64
        image: mysql:5.7
        ports:
          - "3306:3306"
        depends_on:
          - php8.1
          - php8.2
        volumes:
          - ./docker/mysql:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
          - backend
  mysql8.1:
        platform: linux/x86_64
        image: mysql:8.1.0
        ports:
          - "3307:3306"
        depends_on:
          - php8.1
          - php8.2
        volumes:
          - ./docker/mysql8_1:/var/lib/mysql8.1
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
          - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      #PMA_USER: root
      #PMA_PASSWORD: "12345678"
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      - backend
  redis:
        image: arm64v8/redis
        ports:
          - "6379:6379"
        volumes:
          - ./docker/redis:/data
        networks:
          - backend
  redisui:
    image: patrikx3/p3x-redis-ui:latest
    ports:
      - "7843:7843"
    volumes:
      - ./docker/p3x-redis-ui-settings:/settings
    networks:
      - backend
  elastic:
        image: elasticsearch:7.17.1
        ports:
          - "9200:9200"
          - "9300:9300"
        environment:
          - discovery.type=single-node
          - elastic_container=true
        networks:
          - backend
networks:
  backend:
    driver: bridge
